#
# Travis CI job configuration.
#
# https://travis-ci.org/
#

language: java

jdk:
    - oraclejdk7

script:
    - mvn -f modules/pom.xml -DskipTests=false

cache:
    - directories:
        - $HOME/.m2

