== The Tea Scripting Language

Tea is a scripting language for the Java environment.

This document contains instructions on how to setup the development
environment for working on Tea itself. It is intended for the Tea
development team.

This development tree is for the 4.y.z master development branch.





== Pre-Requisites

* JDK 1.6
* Maven 3.0.x





== Preparing the Development Environment

These instructions apply to unix-like environments. If you really want to
develop under windows you should have Cygwin (http://www.cygwin.com/)
installed on your system.


Fetch the source tree from the Git repository hosted at GitHub

----
git clone git@github.com:jorgefranconunes/tea.git
----





== Building

To perform a full build just run `mvn` at the root of the working
copy.

By default unit tests are not run. To run the unit tests as part of
the build define the system property `skipTests=false`, like this:

----
mvn -DskipTests=false
----


In addition there are some Maven profiles that can be activated to
perform specific tasks.

* `-P tea-setup` : Sets up the working area as a Tea
   installation. This is required for running the `teadoc` tool
   (e.g. when the `tea-teadoc` Maven profile is active).

* `-P tea-tunit-tests` : Runs TUnit tests, even when `skipTests=true`
   (which is, by default).

* `-P tea-teadoc` : Creates Teadoc documentation from the project
   source files. The Teadoc documentation is created under
   'doc/teadoc'. This is tipically used when building a release.

* `-P tea-javadoc` : Creates Javadoc documentation from the project
   source files. The Javadoc documentation is created under
   'doc/javadoc'. This is tipically used when building a release.

* `-P tea-build-release` : Creates the tarball of a Tea release.





== Making a New Release

. Check the release version number. Ensure that the version number is
coherent in `config/tea-core.conf` and `pom.xml`.

. Build the release bundle by invoking Maven like this:
+
----
mvn -DteaRelease
----

. The release tarbal is created as './target/tea-4.x.y.tar.bz2'.





== Bug reports

Send your bug reports and requests for new features to
tea.dev@pdmfc.com

