###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "com.pdmfc.tea.runtime" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





PACKAGE_DIR := com/pdmfc/tea/runtime

SOURCES := \
	SArgvUtils.java	\
	SBreakException.java	\
	SContext.java	\
	SContinueException.java	\
	SEmptyListException.java	\
	SEncodingUtils.java	\
	SExitException.java	\
	SFlowControlException.java	\
	SLambdaFunction.java	\
	SLambdaFunctionVarArg.java	\
	SLibVarUtils.java	\
	SMalformedListException.java	\
	SModuleUtils.java	\
	SNoSuchFunctionException.java	\
	SNoSuchVarException.java	\
	SNumArgException.java	\
	SObjBlock.java	\
	SObjByteArray.java	\
	SObjFunction.java	\
	SObjNull.java	\
	SObjPair.java	\
	SObjSymbol.java	\
	SObjVar.java	\
	SReturnException.java	\
	SRuntimeException.java	\
	STeaRuntime.java	\
	STypeException.java	\
	STypes.java	\
	SUtils.java	\

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

