###########################################################################
#
# Copyright (c) 2005-2009 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "com.pdmfc.tea.apps" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





SOURCES= \
	STeaLauncher.java	\
	STeaLauncherArgs.java	\
	STeaShell.java

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

