###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "xml" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
###########################################################################





PACKAGE_DIR := xml

SOURCES := \
	TDocument.tea \
	TDomParser.tea \
	TElement.tea \
	TNode.tea \
	TProcessingInstruction.tea \
	TText.tea \
	utils.tea \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

