###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "lib.tea.net" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





PACKAGE_DIR := lib/tea/net

SOURCES := \
	TServerSocket.tea \
	TSocket.tea \
	TSslSocket.tea \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

