###########################################################################
#
# Copyright (c) 2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "lib.tea.tea.util" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2010/03/01 Created. (jfn)
#
###########################################################################





PACKAGE_DIR := lib/tea/tea/util

SOURCES := \
	lists.tea \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

