###########################################################################
#
# Copyright (c) 2005 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id: Makefile,v 1.1 2005/02/15 17:42:46 jfn Exp $
#
# Makefile for the "lib.tea.util" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





SOURCES = \
	TDocument.tea \
	TDomParser.tea \
	TElement.tea \
	TNode.tea \
	TProcessingInstruction.tea \
	TText.tea \
	utils.tea \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

