###########################################################################
#
# Copyright (c) 2005 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id: Makefile,v 1.1 2005/02/15 17:42:46 jfn Exp $
#
# Makefile for the "com.pdmfc.tea.util" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





SOURCES = \
	SFormater.java \
	SList.java \
	SListNode.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

