###########################################################################
#
# Copyright (c) 2005 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id: Makefile,v 1.1 2005/12/05 20:37:53 pcorreia Exp $
#
# Makefile for the "com.pdmfc.tea.modules.reflect" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# $Log: Makefile,v $
# Revision 1.1  2005/12/05 20:37:53  pcorreia
# Support for reflection over Java
#
#
###########################################################################





SOURCES = \
	SModuleReflect.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

