###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "com.pdmfc.tea.modules.reflect" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/12/05 Support for reflection over Java. (pcorreia)
#
###########################################################################





PACKAGE_DIR := com/pdmfc/tea/modules/reflect

SOURCES := \
	SModuleReflect.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

