###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "com.pdmfc.tea.modules.io" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





PACKAGE_DIR := com/pdmfc/tea/modules/io

SOURCES := \
	SFileInput.java \
	SFileOutput.java \
	SIOException.java \
	SInput.java \
	SModuleIO.java \
	SOutput.java \
	SUrlInput.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

