###########################################################################
#
# Copyright (c) 2005-2008 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "com.pdmfc.tea.compiler" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





SOURCES= \
	SArithExpression.java \
	SCode.java \
	SCompileException.java \
	SCompiler.java \
	SStatement.java \
	SStatementFactory.java	\
	SWord.java \
	SWordBlock.java \
	SWordCmdSubst.java \
	SWordExpression.java \
	SWordExpressionBlock.java \
	SWordFloat.java \
	SWordInt.java \
	SWordList.java \
	SWordLong.java \
	SWordString.java \
	SWordSymbol.java \
	SWordVarSubst.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

