###########################################################################
#
# Copyright (c) 2005 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id: Makefile,v 1.1 2005/02/15 17:42:45 jfn Exp $
#
# Makefile for the "com.pdmfc.tea.modules" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





SOURCES= \
	SModule.java \
	SModuleHtml.java \
	SModuleList.java \
	SModuleMath.java \
	SModuleRegexp.java \
	SModuleString.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

