###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "com.pdmfc.tea.modules.tdbc" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





PACKAGE_DIR := com/pdmfc/tea/modules/tdbc

SOURCES := \
	SCallableStatement.java \
	SClosedEventListener.java \
	SConnection.java \
	SConnectionClass.java \
	SModuleTdbc.java \
	SPreparedStatement.java \
	SResultSet.java \
	SStatement.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

