###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "com.pdmfc.tea.modules" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
#
# Revisions:
#
# 2005/02/15 Created. (jfn)
#
###########################################################################





PACKAGE_DIR := com/pdmfc/tea/modules

SOURCES := \
	SModule.java \
	SModuleHtml.java \
	SModuleList.java \
	SModuleMath.java \
	SModuleRegexp.java \
	SModuleString.java \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

