###########################################################################
#
# Copyright (c) 2005-2010 PDM&FC, All Rights Reserved.
#
###########################################################################

###########################################################################
#
# $Id$
#
# Makefile for the "util" package.
#
# The following variables are expected to be defined:
#
# BASE_DIR - The project root directory.
#
###########################################################################





PACKAGE_DIR := util

SOURCES := \
	TConfiguration.tea \
	THashtable.tea \
	tea-autoload.tea \
	tea-conf.tea \

include $(BASE_DIR)/make/package.make





###########################################################################
#
# 
#
###########################################################################

